import { IngredientType, TIngredient } from '../types';

export const mockedIngredients: Array<TIngredient> = [
  {
    calories: 420,
    carbohydrates: 33,
    fat: 244,
    image: 'https://code.s3.yandex.net/react/code/meat-02.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
    name: 'Мясо бессмертных моллюсков Protostomia',
    price: 1337,
    proteins: 433,
    type: IngredientType.main,
    __v: 0,
    _id: '60d3b41abdacab0026a733c9',
  },
  {
    calories: 643,
    carbohydrates: 85,
    fat: 26,
    image: 'https://code.s3.yandex.net/react/code/meat-03.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
    name: 'Филе Люминесцентного тетраодонтимформа',
    price: 988,
    proteins: 44,
    type: IngredientType.main,
    __v: 0,
    _id: '60d3b41abdacab0026a733c8',
  },
  {
    calories: 643,
    carbohydrates: 85,
    fat: 26,
    image: 'https://code.s3.yandex.net/react/code/bun-01.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-01-large.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
    name: 'Флюоресцентная булка R2-D3',
    price: 988,
    proteins: 44,
    type: IngredientType.bun,
    __v: 0,
    _id: '60d3b41abdacab0026a733c7',
  },
  {
    calories: 643,
    carbohydrates: 85,
    fat: 26,
    image: 'https://code.s3.yandex.net/react/code/bun-01.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-01-large.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
    name: 'Флюоресцентная булка R2-D3',
    price: 988,
    proteins: 44,
    type: IngredientType.bun,
    __v: 0,
    _id: '60d3b41abdacab0026a733c7',
  },
];
